/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Lenovo
 */
public class Menus extends javax.swing.JPanel {

    /**
     * Creates new form Menus
     */
    public Menus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanel_menu = new javax.swing.JPanel();
        jbtn_ajustes = new javax.swing.JButton();
        jbtn_productos = new javax.swing.JButton();
        jbtn_proveedores = new javax.swing.JButton();
        jbtn_clientes = new javax.swing.JButton();
        jbtn_restarar = new javax.swing.JButton();
        jbtn_punto_venta = new javax.swing.JButton();

        jpanel_menu.setBackground(new java.awt.Color(255, 204, 204));

        jbtn_ajustes.setBackground(new java.awt.Color(255, 204, 204));
        jbtn_ajustes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imges/MenuSalir.png"))); // NOI18N
        jbtn_ajustes.setBorder(null);

        jbtn_productos.setBackground(new java.awt.Color(255, 204, 204));
        jbtn_productos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imges/icono_producto_1.png"))); // NOI18N
        jbtn_productos.setBorder(null);
        jbtn_productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_productosActionPerformed(evt);
            }
        });

        jbtn_proveedores.setBackground(new java.awt.Color(255, 204, 204));
        jbtn_proveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imges/Proveedores.png"))); // NOI18N
        jbtn_proveedores.setBorder(null);

        jbtn_clientes.setBackground(new java.awt.Color(255, 204, 204));
        jbtn_clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imges/icono_cliente.png"))); // NOI18N
        jbtn_clientes.setBorder(null);

        jbtn_restarar.setBackground(new java.awt.Color(255, 204, 204));
        jbtn_restarar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imges/recycle_empty_64.png"))); // NOI18N
        jbtn_restarar.setBorder(null);
        jbtn_restarar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_restararActionPerformed(evt);
            }
        });

        jbtn_punto_venta.setBackground(new java.awt.Color(255, 204, 204));
        jbtn_punto_venta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imges/icono_venta.png"))); // NOI18N
        jbtn_punto_venta.setBorder(null);
        jbtn_punto_venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_punto_ventaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanel_menuLayout = new javax.swing.GroupLayout(jpanel_menu);
        jpanel_menu.setLayout(jpanel_menuLayout);
        jpanel_menuLayout.setHorizontalGroup(
            jpanel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_menuLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jpanel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtn_productos, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_punto_venta, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jpanel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel_menuLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jbtn_proveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanel_menuLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jbtn_restarar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(119, 119, 119)
                .addGroup(jpanel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtn_clientes, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(jbtn_ajustes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(109, 156, Short.MAX_VALUE))
        );
        jpanel_menuLayout.setVerticalGroup(
            jpanel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_menuLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jpanel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtn_productos, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_clientes)
                    .addComponent(jbtn_proveedores))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addGroup(jpanel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_menuLayout.createSequentialGroup()
                        .addGroup(jpanel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jbtn_punto_venta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtn_restarar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(109, 109, 109))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_menuLayout.createSequentialGroup()
                        .addComponent(jbtn_ajustes, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanel_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanel_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_productosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_productosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_productosActionPerformed

    private void jbtn_restararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_restararActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_restararActionPerformed

    private void jbtn_punto_ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_punto_ventaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_punto_ventaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jbtn_ajustes;
    public javax.swing.JButton jbtn_clientes;
    public javax.swing.JButton jbtn_productos;
    public javax.swing.JButton jbtn_proveedores;
    public javax.swing.JButton jbtn_punto_venta;
    public javax.swing.JButton jbtn_restarar;
    public javax.swing.JPanel jpanel_menu;
    // End of variables declaration//GEN-END:variables
}
